# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
theme: jekyll-theme-cayman
repository: odpi/egeria
plugins:
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
exclude:
  - open-metadata-resources/open-metadata-deployment/sample-data/**.yml
  - open-metadata-resources/open-metadata-deployment/ansible-egeria/**.yml
